services:
  news-service:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: docker/Dockerfile.service
    container_name: news-service
    ports:
      - "8000:8000"
    env_file:
      - .env # Explicitly specify env file (optional if using default .env)
    environment:
      # MongoDB
      MONGODB_URI: ${MONGODB_URI:-mongodb://localhost:27017/}
      MONGODB_DB: ${MONGODB_DB:-news_agent}
      MONGODB_COLLECTION: ${MONGODB_COLLECTION:-news_items}

      # Environment
      ENV: ${ENV:-production}
